import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

import 'tables/workout_tables.dart';
import 'tables/nutrition_tables.dart';

part 'app_database.g.dart'; // generated by drift_dev

/// FitCore 主資料庫（SQLite + Drift ORM）
/// 所有資料本地優先儲存，可選同步至 Supabase
@DriftDatabase(tables: [
  WorkoutSessions,
  WorkoutSets,
  Programs,
  ProgramDays,
  ProgramExercises,
  UserProfiles,
  NutritionLogs,
])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());
  AppDatabase.forTesting(super.executor);

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (m) async {
      await m.createAll();
      // 插入預設用戶資料
      await into(userProfiles).insert(UserProfilesCompanion.insert(
        createdAt: DateTime.now(),
      ));
    },
    onUpgrade: (m, from, to) async {
      // 未來 schema 升級邏輯
    },
  );
}

/// Drift 開啟本地 SQLite 連接
LazyDatabase _openConnection() => LazyDatabase(() async {
  final dir = await getApplicationDocumentsDirectory();
  final file = File(p.join(dir.path, 'fitcore.db'));
  return NativeDatabase.createInBackground(file);
});

/// Riverpod Provider
final appDatabaseProvider = Provider<AppDatabase>(
  (ref) => throw UnimplementedError('Override in main()'),
);
